#!/usr/bin/env bash

if [ "$UID" -ne 0 ]; then
	if which sudo &> /dev/null; then
		exec sudo "$0" "$@"
	fi
	echo 'Run me as root.'
	exit 1
fi

scriptDir="$(dirname "$(readlink -e "$BASH_SOURCE")")"
if [ -f "$scriptDir/bin/activate" ]; then # If virtualenv exists
	source "$scriptDir/bin/activate"
fi
export PYTHONPATH="$scriptDir/src:$PYTHONPATH"
if [ "$(basename "$0")" == 'tunnelsd' ]; then
	exec python -m tunnels --daemon "$@"
fi
exec python -OO -B -m tunnels "$@"
